config/routes.rb
Rails.application.routes.draw do

  root to: 'lists#index'

  # root to: 'bookmarks#new'

  # root to: 'bookmarks#create'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  # get "movies", to: "movies#index"

  # get "bookmarks", to: "bookmarks#new"

  # post "bookmarks", to: "bookmarks#create"

  # delete "bookmarks", to: "bookmarks#destroy"

  # get "lists", to: "lists#index"

  # get "lists", to: "lists#new"

  # get "lists", to: "lists#show", as: :movie_id

  # post "lists", to: "lists#create"

  resources :movies
  resources :lists, only: [:index, :new, :create, :show] do
    resources :bookmarks, only: [:new, :create]
  end
  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :list
  belongs_to :movie

  validates :comment, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks

  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_list, only: [:create, :new]

  def new
    # @bookmark = Bookmark.find(params[:list_id, :movie_id])
    @bookmark = Bookmark.new
    redirect_to new_list_path(@bookmark.list_id), status: :see_other
  end

  def create
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to movies_path(@bookmark.movie), status: :see_other
  end


  private

  # def set_movie
  #   @movie = Movie.find(params[:movie_id])
  # end

  def set_list
    @list = List.find(params[:list_id])
  end

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  # before_action :set_bookmark, only: [:create]

  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end


  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end



  private

  def list_params
    params.require(:list).permit(:name)
  end

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

  def index
    @movies = Movie.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/bookmarks/new.html.erb
<h2>Bookmarks of Movies</h2>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<h2>List of Movies </h2>

<% @lists.each do |list|%>
  <%= link_to list.name, list_path(list)%>
<% end %>

<%= link_to "Create a list", new_list_path %>

app/views/lists/new.html.erb
<h2>Create a new List</h2>

<%= simple_form_for(@list) do |f| %>
  <%= f.input :name %>
  <%= f.submit %>
<% end %>

app/views/lists/show.html.erb
<h1><%= @list.name %></h1>

<h2>Movies:</h2>

<%= simple_form_for([@list, @bookmark]) do |f| %>
  <%= f.input :comment %>
  <%= f.association :movie %>
  <%= f.submit %>
<% end %>


<% if @list.bookmarks.empty? %>
  <p>No Movies in this List</p>
<% else %>
  <%= @list.bookmarks.each do |bookmark| %>
  <div>
    <p><%= bookmark.movie.title %></p>
    <p><%= bookmark.comment %></p>
  </div>
  <% end %>
<% end %>

app/views/movies/index.html.erb
<h2>Movies:</h2>

app/views/movies/show.html.erb
<%= render @movie %>

<p><Strong> List of Movies</Strong></p>
<ul class="list-group">
  <% @movie.lists.each do |list| %>
    <li class="list-group-item">
      <%= list.name %>
    </li>
  <% end %>
</ul>

<div>
  <%= link_to "See all Movies", lists_path %>
</div>